version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://chatuser:chatpass@db:5432/e2echat
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
    depends_on:
      - db
      - redis
    networks:
      - e2e-chat-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpass
      - POSTGRES_DB=e2echat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - e2e-chat-network

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - e2e-chat-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - e2e-chat-network

volumes:
  postgres_data:
  redis_data:

networks:
  e2e-chat-network:
    driver: bridge